### ISSUE TITLE
Create OC App and add it to DevStock

### ISSUE THREAD

**Issue by thepeak99** [pondersource/dav-token-access#1]

**Comment by navid-shokri** [comment]
ℹ 
this is my instruction to create my app skeleton
https://doc.owncloud.com/server/next/developer_manual/app/tutorial/development_environment.html

**Comment by navid-shokri** [comment]
💥
Remember that the app `id` in info.xml **MUST** be the same as the application root folder. 
Otherwise, none of the exposed routes will be resolved.

**Comment by navid-shokri** [comment]
ℹ 
@MahdiBaghbani add the project to the dev-stock repository. 
and I could run that with these commands: 
```shell

./scripts/init-rc-mounts.sh
./scripts/testing-rc-mounts.sh
```

**Comment by MahdiBaghbani** [comment]
It is added.
